### ISSUE TITLE
No charging or location information

### ISSUE THREAD

**Issue by dgcaste** [teslabout/teslabout-bug-tracker#5]
Not sure if it’s not developed but it goes from general info straight to climate. Nothing on charging or GPS.

**Comment by jjsoviet** [comment]
Last Charge Session and Last Trip data will only be available if there was an actual charging scenario or a recent movement of the vehicle since you've registered. 

However, you do bring up a point: we need to provide messages for no data displayed and an option to wake the car for initial signups in order to populate initial data.

**Comment by dgcaste** [comment]
Well I was charging when I signed up and still charging right now

**Comment by jjsoviet** [comment]
I see, @joeypoon will know more about the specific logic on when our backend starts sending data for charge sessions.

**Comment by joeypoon** [comment]
I'll take a look. It's possible we're not handling the situation where a vehicle onboards while charging.

**Comment by joeypoon** [comment]
Added additional logic to handle vehicle onboarding while charging and driving(I hope this doesn't happen).
